apiVersion: alertmanager.mimir.crossplane.io/v1alpha1
kind: Config
metadata:
  name: example-alertmanager-config
spec:
  forProvider:
    # Configuration for Grafana Mimir Alertmanager
    receiver:
    - name: default
    route:
    - receiver: default
  providerConfigRef:
    name: default
